### ISSUE TITLE
Ambiguous call in InRiverRestClient

### ISSUE THREAD

**Issue by Castleburg** [robert-bialy/inriver-rest-client#8]
The basic InRiverRestClient setup using only API-key has an ambiguous call.

![image](https://user-images.githubusercontent.com/24894873/210055229-9839ce72-91cf-484e-a6b5-6ee884e50ff8.png)

**Comment by robert-bialy** [comment]
Good find, thank you for pointing that out. I will fix it in upcoming version.

**Comment by robert-bialy** [comment]
Fixed in v1.0.2
